<?xml version = "1.0"?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro" name = "snake_robot">

  <!--  Author: Chaitanya Pb

        This Xacro file is a complete XML description of the snake robot used for simulation in Gazebo or RViz.

        Uses these files to run: snake_module.xacro and robot_tags.gazebo

        Doesn't contain paths to external files.  -->

	<xacro:property name = "pi" value = "3.1416"/>

	<xacro:property name = "length" value = "0.05"/>
	<xacro:property name = "width" value = "0.1"/>
	<xacro:property name = "thick" value = "0.0075"/>
	<xacro:property name = "axel_radius" value = "0.0025"/>
	<xacro:property name = "wheel_radius" value = "0.025"/>
	<xacro:property name = "wheel_length" value = "${width/3}"/>

	<xacro:property name = "plate_mass" value = "0.25"/>
	<xacro:property name = "bar_mass" value = "${(thick/width)*plate_mass}"/>
	<xacro:property name = "axel_mass" value = "0.01"/>
	<xacro:property name = "wheel_mass" value = "0.05"/>
	<xacro:property name = "servo_mass" value = "0.001"/>

	<xacro:include filename = "snake_module.xacro"/>

	<gazebo>
      <plugin name = "gazebo_ros_control" filename = "libgazebo_ros_control.so">
        <robotNamespace>/snake_robot</robotNamespace>
      </plugin>
    </gazebo>

	<xacro:create_snake_module prefix = ""/>

	<xacro:create_snake_module prefix = "2"/>
	<joint name = "base_to_2" type = "revolute">
		<parent link = "servo_motor"/>
		<child link = "2base_link"/>
		<origin xyz = "0 0 ${length}" rpy = "0 ${pi} 0"/>
		<axis xyz = "0 0 1"/>
		<limit effort = "1000.0" lower = "-${pi/4}" upper = "${pi/4}" velocity = "0.5"/>
	</joint>
	<transmission name = "b_2_tran">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name = "base_to_2">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name = "b_2_servo">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<xacro:create_snake_module prefix = "3"/>
	<joint name = "2_to_3" type = "revolute">
		<parent link = "2servo_motor"/>
		<child link = "3base_link"/>
		<origin xyz = "0 0 ${length}" rpy = "0 ${pi} 0"/>
		<axis xyz = "0 0 1"/>
		<limit effort = "1000.0" lower = "-${pi/4}" upper = "${pi/4}" velocity = "0.5"/>
	</joint>
	<transmission name = "2_3_tran">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name = "2_to_3">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name = "2_3_servo">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<xacro:create_snake_module prefix = "4"/>
	<joint name = "3_to_4" type = "revolute">
		<parent link = "3servo_motor"/>
		<child link = "4base_link"/>
		<origin xyz = "0 0 ${length}" rpy = "0 ${pi} 0"/>
		<axis xyz = "0 0 1"/>
		<limit effort = "1000.0" lower = "-${pi/4}" upper = "${pi/4}" velocity = "0.5"/>
	</joint>
	<transmission name = "3_4_tran">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name = "3_to_4">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name = "3_4_servo">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<xacro:create_snake_module prefix = "5"/>
	<joint name = "4_to_5" type = "revolute">
		<parent link = "4servo_motor"/>
		<child link = "5base_link"/>
		<origin xyz = "0 0 ${length}" rpy = "0 ${pi} 0"/>
		<axis xyz = "0 0 1"/>
		<limit effort = "1000.0" lower = "-${pi/4}" upper = "${pi/4}" velocity = "0.5"/>
	</joint>
	<transmission name = "4_5_tran">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name = "4_to_5">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name = "4_5_servo">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<xacro:create_snake_module prefix = "6"/>
	<joint name = "5_to_6" type = "revolute">
		<parent link = "5servo_motor"/>
		<child link = "6base_link"/>
		<origin xyz = "0 0 ${length}" rpy = "0 ${pi} 0"/>
		<axis xyz = "0 0 1"/>
		<limit effort = "1000.0" lower = "-${pi/4}" upper = "${pi/4}" velocity = "0.5"/>
	</joint>
	<transmission name = "5_6_tran">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name = "5_to_6">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name = "5_6_servo">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<xacro:create_snake_module prefix = "7"/>
	<joint name = "6_to_7" type = "revolute">
		<parent link = "6servo_motor"/>
		<child link = "7base_link"/>
		<origin xyz = "0 0 ${length}" rpy = "0 ${pi} 0"/>
		<axis xyz = "0 0 1"/>
		<limit effort = "1000.0" lower = "-${pi/4}" upper = "${pi/4}" velocity = "0.5"/>
	</joint>
	<transmission name = "6_7_tran">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name = "6_to_7">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name = "6_7_servo">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<xacro:create_snake_module prefix = "8"/>
	<joint name = "7_to_8" type = "revolute">
		<parent link = "7servo_motor"/>
		<child link = "8base_link"/>
		<origin xyz = "0 0 ${length}" rpy = "0 ${pi} 0"/>
		<axis xyz = "0 0 1"/>
		<limit effort = "1000.0" lower = "-${pi/4}" upper = "${pi/4}" velocity = "0.5"/>
	</joint>
	<transmission name = "7_8_tran">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name = "7_to_8">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name = "7_8_servo">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<link name="head_sonar">
    	<visual>
      		<geometry>
        		<box size="${length/3} ${width/2} ${3*thick}"/>
      		</geometry>
      		<material name="blue">
      			<color rgba = "0 0 1 1"/>
      		</material>
    	</visual>
    </link>
    <joint name="head_sonar_joint" type="fixed">
    	<origin xyz="0 0 ${2*thick}" rpy="0 0 ${pi}"/>
    	<parent link="base_link"/>
    	<child link="head_sonar"/>
  	</joint>

	<xacro:include filename = "robot_tags.gazebo"/>

</robot>