<?xml version = "1.0"?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro" name = "snake_module">

  <!--  Author: Chaitanya Pb

        This Xacro file is a complete XML description of a single module of the snake robot used for simulation 
        in Gazebo or RViz.

        Uses these files to run: module_tags.gazebo

        Should be run only from inside snake_robot.xacro

        Doesn't contain paths to external files.  -->

	<xacro:macro name = "create_box" params = "bname len wid thk mass clr">
		<link name = "${bname}">
			<visual>
				<geometry>
					<box size = "${len} ${wid} ${thk}"/>
				</geometry>
				<material name = "">
					<color rgba = "${clr} 1"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<box size = "${len} ${wid} ${thk}"/>
				</geometry>
			</collision>
			<inertial>
				<mass value = "${mass}"/>
				<inertia ixx = "${(mass*((wid*wid)+(thk*thk)))/12}" ixy = "0.0" ixz = "0.0" 
					iyy = "${(mass*((len*len)+(thk*thk)))/12}" iyz = "0.0" 
					izz = "${(mass*((wid*wid)+(len*len)))/12}"/>
			</inertial>
		</link>
	</xacro:macro>

	<xacro:macro name = "create_cyl" params = "cname len rad mass clr">
		<link name = "${cname}">
			<visual>
				<geometry>
					<cylinder length = "${len}" radius = "${rad}"/>
				</geometry>
				<material name = "">
					<color rgba = "${clr} 1"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<cylinder length = "${len}" radius = "${rad}"/>
				</geometry>
			</collision>
			<inertial>
				<mass value = "${mass}"/>
				<inertia ixx = "${(mass*((3*rad*rad)+(len*len)))/12}" ixy = "0.0" ixz = "0.0" 
					iyy = "${(mass*((3*rad*rad)+(len*len)))/12}" iyz = "0.0" 
					izz = "${(mass*rad*rad)/2}"/>
			</inertial>
		</link>
	</xacro:macro>

	<xacro:macro name = "create_snake_module" params = "prefix">

		<xacro:create_box bname = "${prefix}base_link" len = "${length}" wid = "${width}" thk = "${thick}" mass = "${plate_mass}" clr = "0.97 0.95 0.20"/>
		<xacro:create_box bname = "${prefix}base_bar1" len = "${length}" wid = "${thick}" thk = "${thick}" mass = "${bar_mass}" clr = "0.97 0.95 0.20"/>
		<xacro:create_box bname = "${prefix}base_bar2" len = "${length}" wid = "${thick}" thk = "${thick}" mass = "${bar_mass}" clr = "0.97 0.95 0.20"/>
		
		<joint name = "${prefix}base_to_bbar1" type = "fixed">
			<parent link = "${prefix}base_link"/>
			<child link = "${prefix}base_bar1"/>
			<origin xyz = "${length} ${(width-thick)/2} 0"/>
		</joint>
		
		<joint name = "${prefix}base_to_bbar2" type = "fixed">
			<parent link = "${prefix}base_link"/>
			<child link = "${prefix}base_bar2"/>
			<origin xyz = "${length} -${(width-thick)/2} 0"/>
		</joint>

		<xacro:create_box bname = "${prefix}step_link" len = "${length}" wid = "${width}" thk = "${thick}" mass = "${plate_mass}" clr = "0.97 0.95 0.20"/>
		<xacro:create_box bname = "${prefix}step_bar1" len = "${length}" wid = "${thick}" thk = "${thick}" mass = "${bar_mass}" clr = "0.97 0.95 0.20"/>
		<xacro:create_box bname = "${prefix}step_bar2" len = "${length}" wid = "${thick}" thk = "${thick}" mass = "${bar_mass}" clr = "0.97 0.95 0.20"/>

		<joint name = "${prefix}bbar1_to_sbar1" type = "fixed">
			<parent link = "${prefix}base_bar1"/>
			<child link = "${prefix}step_bar1"/>
			<origin xyz = "${length/2} 0 ${(length-thick)/2}" rpy = "0 ${pi/2} 0"/>
		</joint>

		<joint name = "${prefix}bbar2_to_sbar2" type = "fixed">
			<parent link = "${prefix}base_bar2"/>
			<child link = "${prefix}step_bar2"/>
			<origin xyz = "${length/2} 0 ${(length-thick)/2}" rpy = "0 ${pi/2} 0"/>
		</joint>

		<joint name = "${prefix}sbar1_to_step" type = "fixed">
			<parent link = "${prefix}step_bar1"/>
			<child link = "${prefix}step_link"/>
			<origin xyz = "-${length} -${(width-thick)/2} 0" rpy = "0 0 0"/>
		</joint>

		<xacro:create_box bname = "${prefix}ceil_link" len = "${2*length}" wid = "${width}" thk = "${thick}" mass = "${2*plate_mass}" clr = "0.97 0.95 0.20"/>

		<joint name = "${prefix}step_to_ceil" type = "fixed">
			<parent link = "${prefix}step_link"/>
			<child link = "${prefix}ceil_link"/>
			<origin xyz = "-${(length+thick)/2} 0 ${length-(thick/2)}" rpy = "0 ${pi/2} 0"/>
		</joint>

		<xacro:create_cyl cname = "${prefix}wheel_axel" len = "${width-(2*thick)}" rad = "${axel_radius}" mass = "${axel_mass}" clr = "0 0 0"/>
		<xacro:create_cyl cname = "${prefix}wheel" len = "${wheel_length}" rad = "${wheel_radius}" mass = "${wheel_mass}" clr = "1 1 1"/>
		<xacro:create_cyl cname = "${prefix}servo_motor" len = "${(2*length)-thick}" rad = "${wheel_radius/4}" mass = "${servo_mass}" clr = "0 0 0"/>

		<joint name = "${prefix}bbar2_to_axel" type = "fixed">
			<parent link = "${prefix}base_bar2"/>
			<child link = "${prefix}wheel_axel"/>
			<origin xyz = "${length/2} ${(width-thick)/2} 0" rpy = "${pi/2} 0 0"/>
		</joint>

		<joint name = "${prefix}axel_to_wheel" type = "continuous">
			<parent link = "${prefix}wheel_axel"/>
			<child link = "${prefix}wheel"/>
			<origin xyz = "0 0 0" rpy = "0 0 0"/>
			<axis xyz = "0 0 1"/>
		</joint>

		<joint name = "${prefix}ceil_to_servo" type = "fixed">
			<parent link = "${prefix}ceil_link"/>
			<child link = "${prefix}servo_motor"/>
			<origin xyz = "-${length/2} 0 ${length}" rpy = "0 0 0"/>
		</joint>

		<xacro:create_box bname = "${prefix}sonar_left" len = "${length/3}" wid = "${width/2}" thk = "${3*thick}" mass = "0" clr = "0 0 1"/>
		<xacro:create_box bname = "${prefix}sonar_right" len = "${length/3}" wid = "${width/2}" thk = "${3*thick}" mass = "0" clr = "0 0 1"/>
		
	    <joint name="${prefix}sonar_left_joint" type="fixed">
	    	<origin xyz="0 -${width/2} ${2*thick}" rpy="0 ${pi} ${pi/2}"/>
	    	<parent link="${prefix}ceil_link"/>
	    	<child link="${prefix}sonar_left"/>
	  	</joint>

	    <joint name="${prefix}sonar_right_joint" type="fixed">
	    	<origin xyz="0 ${width/2} ${2*thick}" rpy="0 0 ${pi/2}"/>
	    	<parent link="${prefix}ceil_link"/>
	    	<child link="${prefix}sonar_right"/>
	  	</joint>

		<xacro:include filename = "module_tags.gazebo"/>

	</xacro:macro>

</robot>